Repository milieuinfo/webcomponent-vl-ui-data-table, pull requests merged in 2019-09, with the labels that each got.

#18 UIG-218
  vl-data-table.src.js
Labels: maintenance

#19 Update link naar demo
  vl-data-table.src.js
Labels: maintenance

#20 Automatic commit via update script
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  package-lock.json
  package.json
Labels: maintenance

#23 Update dependency vl-ui-core to v1.4.6
  package-lock.json
  package.json
Labels: dependencies

#22 Update dependency @govflanders/vl-ui-util to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#21 Update dependency @govflanders/vl-ui-core to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#8 Update dependency replace to v1.1.0
  package-lock.json
  package.json
Labels: dependencies, renovate

#7 Update dependency np to v3.1.0
  package-lock.json
  package.json
Labels: dependencies, renovate

#24 Update dependency replace to v1.1.1
  package-lock.json
  package.json
Labels: dependencies

#25 Revert naar @govflanders 3.7.2
  package-lock.json
  package.json
Labels: bug

#26 Revert naar @govflanders 3.7.2
  package-lock.json
Labels: bug

#30 Automatic commit via update script
  package-lock.json
Labels: maintenance

#32 Update and install latest util
  .github/ISSUE_TEMPLATE/task.md
  bamboo-specs/bamboo.yml
  demo/demo.css
  package-lock.json
  package.json
  style.css
Labels: maintenance

#35 Update vl-ui-util
  CODEOWNERS
  demo/demo.css
  package-lock.json
  package.json
  style.css
Labels: maintenance
