Repository milieuinfo/webcomponent-vl-ui-data-table, pull requests merged in 2020-07, with the labels that each got.

#77 Update dependency @govflanders/vl-ui-core to v3.10.1
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#78 Update dependency @govflanders/vl-ui-data-table to v3.9.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#79 Update dependency @govflanders/vl-ui-util to v3.10.1
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#76 Introductie e2e functie om tabel rijen inhoud te valideren en dev dependencies update
  dist/style.css
  dist/vl-data-table.js
  dist/vl-data-table.min.js
  dist/vl-data-table.src.js
  package-lock.json
  src/style.css
  test/e2e/components/vl-data-table.js
  test/e2e/data-table.test.js
Labels: enhancement

#80 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
Labels: chore
