Repository milieuinfo/webcomponent-vl-ui-data-table, pull requests merged in 2020-03, with the labels that each got.

#56 E2E testen introductie
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  .gitignore
  .mocharc.js
  demo/vl-data-table.html
  package-lock.json
  package.json
  test/e2e/components/vl-data-table.js
  test/e2e/data-table.test.js
  test/e2e/pages/vl-data-table.page.js
Labels: chore

#57 Update vl-ui-util
  package-lock.json
  package.json
Labels: chore, maintenance

#58 Introductie responsiveness
  demo/vl-data-table.html
  package-lock.json
  src/vl-data-table.js
  test/e2e/components/vl-data-table.js
  test/e2e/data-table.test.js
  test/e2e/pages/vl-data-table.page.js
  test/unit/vl-data-table.test.html
Labels: enhancement

#59 Update vl-ui-core
  demo/performance.html
  docker-compose-performance-chrome.yml
  docker-compose-performance-firefox.yml
  package-lock.json
  package.json
  performance/README.md
  performance/config/budget.json
  performance/config/config-chrome.json
  performance/config/config-firefox.json
  performance/scripts/preScript.js
Labels: chore

#60 Update vl-ui-core
  package-lock.json
  package.json
Labels: chore
