Repository milieuinfo/webcomponent-vl-ui-data-table, pull requests merged in 2020-01, with the labels that each got.

#46 Update vl-ui-util
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.js
  package-lock.json
  package.json
  style.css
  test/docker-compose.yml
  wct.docker.conf.json
  wct.local.conf.json
Labels: maintenance

#47 Update naar laatste util
  package-lock.json
  package.json
Labels: bugfix

#50 Verwijder pretest fase (installeren chromedriver). Deze komt via vl-ui-util binnenDepend op core-branch zonder after
  package.json
Labels: chore

#48 Overbodig NPM release import scripts verwijderd
  package.json
Labels: maintenance

#49 Update vl-ui-util
  demo/demo.css
  package-lock.json
  package.json
  style.css
  test/docker-compose.yml
Labels: maintenance

#51 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance

#52 Update vl-ui-util
  bamboo-specs/bamboo.yml
  docker-compose-release.yml
  package-lock.json
  package.json
Labels: maintenance
